#!/usr/bin/env python3
"""Sanctuary site drift check.

Compares claims in this marketing site to the actual state of
nekoguntai-castle/sanctuary and writes a Markdown report listing
detected drift to drift-report.md (empty file when nothing's drifted).

The accompanying workflow (.github/workflows/sanctuary-drift-check.yml)
runs this weekly and opens or updates an issue when the report is
non-empty.

Add a new check by writing a function that returns a list of
Markdown-formatted strings (one per drift item) and appending it to
CHECKS.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

REPO = "nekoguntai-castle/sanctuary"
SITE_ROOT = Path(__file__).resolve().parent.parent
FEATURES_HTML = SITE_ROOT / "sanctuary" / "features.html"
REPORT_PATH = SITE_ROOT / "drift-report.md"

USER_AGENT = "nekoguntai-html-drift-check"


def gh_api(path: str) -> object:
    req = Request(
        f"https://api.github.com{path}",
        headers={"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"},
    )
    with urlopen(req, timeout=15) as r:
        return json.load(r)


def parse_version(v: str) -> tuple[int, ...]:
    """Return a sortable tuple from a version string like 'v0.8.46' or '0.8.46+'."""
    nums = re.findall(r"\d+", v)
    return tuple(int(n) for n in nums) if nums else (0,)


def latest_sanctuary_tag() -> str | None:
    """Latest semver tag on the sanctuary repo, e.g. 'v0.8.46'."""
    tags = gh_api(f"/repos/{REPO}/tags?per_page=100")
    semver = [t["name"] for t in tags if re.match(r"^v?\d+\.\d+\.\d+$", t["name"])]
    if not semver:
        return None
    return max(semver, key=parse_version)


def newest_version_in_timeline(html: str) -> str | None:
    """Highest semver mentioned anywhere in the features-page timeline."""
    versions = re.findall(r"v(\d+\.\d+\.\d+)\+?", html)
    if not versions:
        return None
    return f"v{max(versions, key=parse_version)}"


def check_release_drift() -> list[str]:
    latest_tag = latest_sanctuary_tag()
    if not latest_tag:
        return ["- WARN — Could not fetch sanctuary release tags."]
    if not FEATURES_HTML.exists():
        return [f"- WARN — `{FEATURES_HTML.relative_to(SITE_ROOT)}` not found."]
    html = FEATURES_HTML.read_text()
    newest_on_site = newest_version_in_timeline(html)
    if not newest_on_site:
        return ["- WARN — No version found in the features-page timeline."]
    if parse_version(latest_tag) > parse_version(newest_on_site):
        return [
            f"- **Timeline behind release.** sanctuary's latest tag is `{latest_tag}`; "
            f"the newest version in the site's Built-so-far timeline is "
            f"`{newest_on_site}`. Update `sanctuary/features.html#timeline`, then "
            f"run `./scripts/version-assets.sh` before committing."
        ]
    return []


CHECKS = [check_release_drift]


def main() -> None:
    findings: list[str] = []
    for check in CHECKS:
        try:
            findings.extend(check())
        except Exception as exc:  # noqa: BLE001  — we want to surface check errors as drift
            findings.append(
                f"- WARN — Check `{check.__name__}` raised "
                f"`{type(exc).__name__}`: {exc}"
            )

    if findings:
        body = "# Sanctuary site drift detected\n\n" + "\n".join(findings) + "\n"
        body += (
            "\n---\n\n_Auto-generated by "
            "`.github/workflows/sanctuary-drift-check.yml`. Run "
            "`python3 scripts/check-sanctuary-drift.py` locally to reproduce._\n"
        )
        REPORT_PATH.write_text(body)
        print(f"drift detected ({len(findings)} item(s)); wrote {REPORT_PATH.name}")
    else:
        REPORT_PATH.write_text("")
        print("no drift detected")


if __name__ == "__main__":
    main()
